site_name: RISKEN
site_url: https://docs.security-hub.jp/
site_author: RISKEN

# Navigation
nav:
  - RISKEN:
    - Overview:
      - RISKEN:    index.md
      - Concept:   risken/overview_concept.md
      - Coverage:  risken/overview_coverage.md
    - Quick Start: risken/quick_start.md
    - Project:     risken/project.md
    - Finding:     risken/finding.md
    - Alert:       risken/alert.md
    - User:        risken/user.md
    - Report:      risken/report.md

  - AWS:
    - Overview:
      - Concept:      aws/overview_aws.md
      - DataSource:   aws/overview_datasource.md
      - IAM Role:     aws/overview_iam.md
      - Scan:         aws/overview_scan.md
    - AccessAnalyzer: aws/accessanalyzer.md
    - AdminChecker:   aws/adminchecker.md
    - CloudSploit:    aws/cloudsploit.md
    - GuardDuty:      aws/guardduty.md
    - PortScan:       aws/portscan.md
    - Activity:
      - Concept:      aws/activity_concept.md
      - Data Types:   aws/activity_data.md
      - Filtering:    aws/activity_filter.md
      - Limitation:   aws/activity_limitation.md

  - Google:
    - Overview:
      - Concept:               google/overview_google.md
      - GCP:                   google/overview_gcp.md
      - ServiceAccount:        google/overview_sa.md
      - DataSource:            google/overview_datasource.md
      - Scan:                  google/overview_scan.md
    - Asset:                   google/asset.md
    - Security Command Center: google/scc.md
    - CloudSploit:             google/cloudsploit.md

  - Diagnosis:
    - Overview:     diagnosis/index.md
    - WPScan:
      - Concept:    diagnosis/wpscan_concept.md
      - DataSource: diagnosis/wpscan_datasource.md
      - Scan:       diagnosis/wpscan_scan.md
    - JIRA:
      - Concept:    diagnosis/jira_concept.md
      - DataSource: diagnosis/jira_datasource.md
      - Scan:       diagnosis/jira_scan.md

  - OSINT:
    - Overview:     osint/index.md
    - Domain:
      - Concept:    osint/domain_concept.md
      - DataSource: osint/domain_datasource.md
      - Scan:       osint/domain_scan.md

  - Code:
    - Overview:     code/index.md
    - Gitleaks:
      - Concept:    code/gitleaks_concept.md
      - DataSource: code/gitleaks_datasource.md
      - Scan:       code/gitleaks_scan.md

  - Contact us:
    - Contact: contact/contact.md
    - FAQ:     contact/faq.md

# Theme
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # scheme: slate # dark
    scheme: default
    primary: white
    accent: white
  language: ja
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.instant
    - navigation.indexes
    - navigation.tracking
    # - navigation.expand
    # - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

# i18n
extra:
  alternate:
    - name: 日本語
      link: /
      lang: ja
    - name: English
      link: /en/
      lang: en
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<risken@cyberagent.co.jp>
      name: RISKEN


# Plugins
plugins:
  - search:
      lang:
        # - en
        - ja

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra_javascript:
  # https://mermaid-js.github.io/mermaid/#/README
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js

extra_css:
  - css/extra.css

copyright: 　&copy; 2021 - 2021 RISKEN
