site_name: RISKEN
site_url: https://docs.security-hub.jp/
site_author: RISKEN

# Navigation
nav:
  - RISKEN:
      - Overview:
          - RISKEN: index.md
          - Concept: risken/overview_concept.md
          - Coverage: risken/overview_coverage.md
      - Quick Start: risken/quick_start.md
      - Project: risken/project.md
      - Organization: risken/organization.md
      - Finding: risken/finding.md
      - AttackFlow: risken/attack_flow.md
      - Alert: risken/alert.md
      - Auto Triage: risken/triage.md
      - User: risken/user.md
      - AccessToken: risken/access_token.md
      - MCP Server: risken/mcp.md
      - User Reservation: risken/user_reservation.md
      - Report: risken/report.md

      - Well-Architected: risken/well_architected.md

  - AWS:
      - Overview:
          - Concept: aws/overview_aws.md
          - DataSource: aws/overview_datasource.md
          - IAM Role: aws/overview_iam.md
          - Scan: aws/overview_scan.md
      - AccessAnalyzer: aws/accessanalyzer.md
      - AdminChecker: aws/adminchecker.md
      - CloudSploit: aws/cloudsploit.md
      - GuardDuty: aws/guardduty.md
      - PortScan: aws/portscan.md

  - Google:
      - Overview:
          - Concept: google/overview_google.md
          - GCP: google/overview_gcp.md
          - ServiceAccount: google/overview_sa.md
          - DataSource: google/overview_datasource.md
          - Scan: google/overview_scan.md
      - Asset: google/asset.md
      - Security Command Center: google/scc.md
      - CloudSploit: google/cloudsploit.md
      - PortScan: google/portscan.md

  - Diagnosis:
      - Overview: diagnosis/index.md
      - WPScan:
          - Concept: diagnosis/wpscan_concept.md
          - DataSource: diagnosis/wpscan_datasource.md
          - Scan: diagnosis/wpscan_scan.md
      - ApplicationScan:
          - Concept: diagnosis/applicationscan_concept.md
          - DataSource: diagnosis/applicationscan_datasource.md
          - Scan: diagnosis/applicationscan_scan.md
      - PortScan:
          - Concept: diagnosis/portscan_concept.md
          - DataSource: diagnosis/portscan_datasource.md
          - Scan: diagnosis/portscan_scan.md

  - OSINT:
      - Overview:
          - Concept: osint/overview_osint.md
          - DataSource: osint/datasource.md
          - Scan: osint/scan.md
      - Domain:
          - Concept: osint/domain_concept.md
      - Website:
          - Concept: osint/website_concept.md

  - Code:
      - Concept: code/index.md
      - GitHub:
          - Setting: code/github_setting.md
          - CodeReviewAutomation: code/github_review_automation.md
      - Gitleaks:
          - Concept: code/gitleaks_concept.md
          - DataSource: code/gitleaks_datasource.md
          - Scan: code/gitleaks_scan.md
      - Dependency:
          - Concept: code/dependency_concept.md
          - DataSource: code/dependency_datasource.md
          - Scan: code/dependency_scan.md
      - CodeScan:
          - Concept: code/codescan_concept.md
          - DataSource: code/codescan_datasource.md
          - Scan: code/codescan_scan.md

  - Azure:
      - Overview:
          - Concept: azure/overview_azure.md
          - ServicePrincipal: azure/overview_sp.md
          - Subscription: azure/overview_subscription.md
          - DataSource: azure/overview_datasource.md
          - Scan: azure/overview_scan.md
      - Prowler: azure/prowler.md

  - Admin:
      - Overview: admin/overview.md
      - AdminMenu:
          - User: admin/admin_user.md
          - Report: admin/admin_report.md
      - Infrastructure:
          - Architecture: admin/infra_architecture.md
          - Local:
              - Installation: admin/infra_local.md
              - Options: admin/infra_local_option.md
          - AWS:
              - Installation: admin/infra_aws.md
              - Options: admin/infra_aws_option.md
          - Tuning: admin/infra_tuning.md
      - Parameters:
          - Index: admin/param_index.md
          - Common: admin/param_common.md
          - Gateway: admin/param_gateway.md
          - Core: admin/param_core.md
          - AWS: admin/param_aws.md
          - Google: admin/param_google.md
          - Diagnosis: admin/param_diagnosis.md
          - OSINT: admin/param_osint.md
          - Code: admin/param_code.md

  - Reference:
      - API: reference/api.md
      - Finding API: reference/api_finding.md
      - Alert API: reference/api_alert.md
      - AWS API: reference/api_aws.md
      - Google API: reference/api_google.md
      - Diagnosis API: reference/api_diagnosis.md
      - Code API: reference/api_code.md
      - IAM API: reference/api_iam.md
      - Project API: reference/api_project.md
      - Report API: reference/api_report.md

  - Contact us:
      - Contact: contact/contact.md
      - Migration: contact/migration.md
      - FAQ: contact/faq.md

# Theme
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # scheme: slate # dark
    scheme: default
    primary: white
    accent: white
  language: ja
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

# i18n
extra:
  alternate:
    - name: 日本語
      link: /
      lang: ja
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<risken@cyberagent.co.jp>
      name: RISKEN
  # Google Analitics
  analytics:
    provider: google
    property: G-Q0YRWEDKYG

# Plugins
plugins:
  - search:
      lang:
        - ja
        - en
  - i18n:
      default_language: ja
      languages:
        ja: 日本語
        en: English

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra_javascript:
  # https://mermaid-js.github.io/mermaid/#/README
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js

extra_css:
  - css/extra.css

copyright: 　&copy; 2021 - 2023 RISKEN
