version: 0.2
env:
  variables:
    IMAGE: "gateway/doc"
    DOCKER_BUILD_OPT: "--no-cache --pull"

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Setting environment variables"
      - TAG=v0.0.${CODEBUILD_BUILD_NUMBER}
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - REGISTORY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

  build:
    commands:
      - echo "Build web started on `date`"
      - cd ${CODEBUILD_SRC_DIR} && docker build ${DOCKER_BUILD_OPT} -t ${IMAGE}:${TAG} .

      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})

      - echo "Tagging the images..."
      - docker tag ${IMAGE}:${TAG} ${REGISTORY}/${IMAGE}:${TAG}
      - docker tag ${IMAGE}:${TAG} ${REGISTORY}/${IMAGE}:latest

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push ${REGISTORY}/${IMAGE}:${TAG}
      - docker push ${REGISTORY}/${IMAGE}:latest

      - echo "Build completed on `date`"
