version: 0.2

env:
  variables:
    IMAGE: "gateway/doc"
    DOCKER_BUILD_OPT: "--no-cache --pull"

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - echo "Build web started on `date`"
      - cd ${CODEBUILD_SRC_DIR} && docker build ${DOCKER_BUILD_OPT} -t ${IMAGE}:test .
